// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calender: typeof import('./src/components/Calender.vue')['default']
    CalenderDay: typeof import('./src/components/CalenderDay.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputHours: typeof import('./src/components/InputHours.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduledCard: typeof import('./src/components/ScheduledCard.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
